node {
   def commit_id
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       sh 'npm install --only=dev'
       sh 'npm test'
     }
   }
   stage("Docker Push"){
      withCredentials([string(credentialsId: 'DOCKER_HUB_CREDENTIAL', variable: 'DOCKER_HUB_CREDENTIAL')]) {
      sh "docker login -u nirmala1234 -p ${DOCKER_HUB_CREDENTIAL}"
      def app = docker.build("nirmala1234/docker-nodejs-demo:${commit_id}", '.').push()
     }
   }
}
